# Generated by Django 3.2.6 on 2023-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230412_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='auth_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='endpoint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='p256dh_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
