# Generated by Django 3.2.6 on 2022-11-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vendor',
            field=models.CharField(default='Ola', max_length=255),
            preserve_default=False,
        ),
    ]
