# Generated by Django 3.2.6 on 2022-11-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_trip_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='unique_id',
        ),
    ]
