# Generated by Django 3.2.6 on 2022-11-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_trip_creator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['departure_date']},
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(help_text='Unconfirmed, Accepted or Rejected', max_length=50),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(help_text='Upcoming or Past', max_length=50),
        ),
    ]
