# Generated by Django 3.2.6 on 2022-11-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221125_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='vacancies',
            field=models.IntegerField(default=0),
        ),
    ]
