# Generated by Django 3.2.6 on 2022-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_trip_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(default='Upcoming', help_text='Upcoming or Past', max_length=50),
        ),
    ]
