# Generated by Django 3.2.6 on 2022-11-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='car_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
