# Generated by Django 3.2.6 on 2022-11-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20221128_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='for_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.trip'),
        ),
    ]
